### This Notebook is for generating graphs, plots, and results fit for our presentation

In [10]:
import pandas as pd
import numpy as np

df_seed = pd.read_csv("data/Seed Results.csv")
df_seed.head()

,SEED,PAKE,PAKE RANK,PASE,PASE RANK,GAMES,W,L,WIN%,R64,R32,S16,E8,F4,F2,CHAMP,TOP2,CHAMP%
0,11,14.2,2,14.8,1,127,59,68,0.465,68,33,16,6,4,0,0,0,11.80%
1,15,3.8,5,5.2,2,80,12,68,0.150,68,7,4,1,0,0,0,0,0.00%
2,3,5.9,3,4.0,3,196,129,67,0.658,68,60,40,20,5,3,1,0,80.70%
3,4,2.5,6,3.8,4,177,110,67,0.621,68,53,37,11,6,2,1,0,75.80%
4,8,-0.3,8,3.0,5,119,51,68,0.429,68,35,7,3,3,3,0,0,16.30%

In [11]:
df_seed[['SEED', 'PAKE RANK', 'PASE RANK', 'WIN%', 'F4', 'CHAMP%']]

    SEED  PAKE RANK  PASE RANK   WIN%  F4  CHAMP%
0     11          2          1  0.465   4  11.80%
1     15          5          2  0.150   0   0.00%
2      3          3          3  0.658   5  80.70%
3      4          6          4  0.621   6  75.80%
4      8          8          5  0.429   3  16.30%
5      9         10          6  0.393   2  12.40%
6     12          4          7  0.352   0   4.60%
7      7          7          8  0.481   3  22.60%
8     16          9          9  0.029   0   0.00%
9     13         11         10  0.200   0   0.60%
10     1          1         11  0.804  28  99.90%
11    10         14         12  0.364   1  13.50%
12    14         13         13  0.105   0   0.50%
13     5         15         14  0.524   5  51.00%
14     2         12         15  0.690  11  97.70%
15     6         16         16  0.433   0  31.20%

In [12]:
df_seed['SEED DIFF'] = df_seed['PAKE RANK'] - df_seed['SEED']
df_seed['HIGH_PERFORMANCE'] = df_seed['SEED DIFF'] < -1
df_seed['LOW_PERFORMANCE'] = df_seed['SEED DIFF'] > 1
df_seed[['SEED', 'PAKE RANK', 'SEED DIFF', 'HIGH_PERFORMANCE', 'LOW_PERFORMANCE']]

    SEED  PAKE RANK  SEED DIFF  HIGH_PERFORMANCE  LOW_PERFORMANCE
0     11          2         -9              True            False
1     15          5        -10              True            False
2      3          3          0             False            False
3      4          6          2             False             True
4      8          8          0             False            False
5      9         10          1             False            False
6     12          4         -8              True            False
7      7          7          0             False            False
8     16          9         -7              True            False
9     13         11         -2              True            False
10     1          1          0             False            False
11    10         14          4             False             True
12    14         13         -1             False            False
13     5         15         10             False             True
14     2         12         10             False             True
15     6         16         10             False             True